[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orr_overpotential_calculator"
version = "0.1.0"
description = "Calculator for ORR overpotential"
requires-python = ">=3.9"
dependencies = [
    "matplotlib",
    "pandas",
    "mace-torch==0.3.13",
    "torch-dftd",
    "ase",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"orr_overpotential_calculator.data" = ["*.yaml"]
